### ISSUE TITLE
Migration to Laminas

### ISSUE THREAD

**Issue by rarog** [tasmaniski/zf2-config-helper#3]
ZF3 is now dead and replaced by Laminas. Will you migrate the project?
The changes should be trivial. The only other thing is that assisted migration by lamias-migration (https://docs.laminas.dev/tutorials/migration-from-zendframework/) expects the package to be tasmaniski/laminas-config-helper as it replaces package names from zend to laminas.

If the project is dead I could of course fork and do my own changes, but having the changes from your source would be of course easier.

**Comment by rarog** [comment]
So far I created a migrated version for my personal use. I could do a pull request if you want.

https://github.com/rarog/laminas-config-helper

**Comment by tasmaniski** [comment]
Hi, I will gladly merge that PR :)

**Comment by rarog** [comment]
I added https://github.com/tasmaniski/zend-config-helper/pull/4, but I integrated package name change. If you want to keep old package name, I can add changes to revert the package name.

**Comment by tasmaniski** [comment]
HI! Thank you for the PR, but unfortunately in your PR unit tests was broken :/ 
I migrated the module now, so feel free to use it or just keep your fork :) 

Thanks!
